{% set package_name = "qtpy-dynamic-font-size-label" %}
{% set import_name = "qtpy_dynamic_font_size_label" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - qtpy
    - pyqt =5

test:
  imports:
    - {{ import_name }}
  requires:
    - pytest

about:
  home: https://github.com/pcdshub/qtpy-dynamic-font-size-label
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: PyQt/PySide dynamic font size QLabel
